# Generated by Django 2.2.3 on 2019-07-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190718_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='articles', to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cathegory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Category'),
        ),
    ]
