# Generated by Django 2.2.3 on 2019-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190718_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='articles', to='shop.Item'),
        ),
    ]
