# Generated by Django 2.2.3 on 2019-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190719_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(related_name='basket', through='shop.ItemInBasket', to='shop.Item'),
        ),
    ]
