# Generated by Django 2.2.3 on 2019-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190723_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(default='no owner', max_length=150),
        ),
    ]
